// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Meus Descontos Online - Todos os Melhores Descontos em um só Lugar",
  description: "Encontre as melhores promoções e descontos do Mercado Livre, Amazon, Magazine Luiza, Americanas, Shopee e AliExpress. Ofertas organizadas e links diretos para economizar.",
  keywords: "promoções Shopee, descontos Amazon, ofertas Mercado Livre, promoções Magazine Luiza, descontos Americanas, ofertas AliExpress, cupons desconto, promoções online",
  authors: [{ name: "Meus Descontos Online" }],
  openGraph: {
    title: "Meus Descontos Online - Melhores Ofertas",
    description: "Acesse rapidamente as melhores promoções dos principais marketplaces do Brasil",
    type: "website",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}